# Generated by Django 4.2.5 on 2023-09-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('contact', models.TextField()),
                ('img', models.ImageField(upload_to='images/%y/%m/%d')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
