# Generated by Django 4.2.5 on 2023-09-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product'},
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, choices=[('كاسات', 'كاسات'), ('بسكوت', 'بسكوت'), ('مشروبات', 'مشروبات')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='contact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
