# Generated by Django 4.2.5 on 2023-09-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_products_options_products_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biscut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('contact', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/biscut/%y/%m/%d')),
                ('active', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, choices=[('photo', 'photo'), ('cupmb', 'cupmb')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Biscut',
            },
        ),
        migrations.CreateModel(
            name='Cups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('contact', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/cups/%y/%m/%d')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cups',
            },
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
