# Generated by Django 4.2.5 on 2023-10-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_biscut_cups_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('contact', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/%y/%m/%d')),
                ('active', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, choices=[('بسكوت', 'بسكوت'), ('كوب', 'كوب')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Product',
            },
        ),
        migrations.DeleteModel(
            name='Biscut',
        ),
        migrations.DeleteModel(
            name='Cups',
        ),
    ]
