# Generated by Django 4.2.5 on 2023-10-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField()),
                ('logo', models.ImageField(upload_to='icons/%y/%m/%d')),
            ],
            options={
                'verbose_name': '',
            },
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
