# Generated by Django 4.2.5 on 2023-10-09 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_work_delete_homepage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='name',
            new_name='العنوان',
        ),
    ]
