# Generated by Django 4.2.5 on 2023-10-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_name_work_العنوان'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='work/%y/%m/%d'),
        ),
    ]
