# Generated by Django 4.2.5 on 2023-10-09 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_work_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={},
        ),
        migrations.RenameField(
            model_name='work',
            old_name='العنوان',
            new_name='title',
        ),
    ]
