# Generated by Django 4.2.5 on 2023-10-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_work_options_rename_العنوان_work_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='icons/%y/%m/%d')),
            ],
            options={
                'verbose_name': 'info',
            },
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Work'},
        ),
    ]
