# Generated by Django 4.2.5 on 2023-10-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_info_alter_work_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='Carousel/%y/%m/%d')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Carousel',
            },
        ),
    ]
