# Generated by Django 4.2.5 on 2023-10-09 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_carousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='active',
        ),
    ]
